import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import SwaggerParser from '@apidevtools/swagger-parser';
import { OpenAPIV3 } from 'openapi-types';
import { McpToolDefinition } from '../src/types';
import { getToolsFromOpenApiDocument } from './generator/api';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Api Document URL */
const DEFAULT_API_DOCUMENT_URL = 'https://api-docs.firefly-iii.org/firefly-iii-6.2.13-v1.yaml';
const LOCAL_SPEC_PATH = path.resolve(__dirname, '../assets/firefly-iii-6.2.13-v1.yaml');
const OUTPUT_FILE = './src/tools.ts';

type SpecSource = {
  label: string;
  location: string;
};

const envFile = process.env.FIREFLY_III_OPENAPI_FILE?.trim();
const envUrl = process.env.FIREFLY_III_OPENAPI_URL?.trim();

const specSources: SpecSource[] = [
  envFile ? { label: 'FIREFLY_III_OPENAPI_FILE', location: envFile } : undefined,
  envUrl ? { label: 'FIREFLY_III_OPENAPI_URL', location: envUrl } : undefined,
  { label: 'Firefly III public OpenAPI URL', location: DEFAULT_API_DOCUMENT_URL },
  { label: 'bundled OpenAPI snapshot', location: LOCAL_SPEC_PATH }
].filter((item): item is SpecSource => Boolean(item));

async function loadOpenApiDocument(): Promise<OpenAPIV3.Document> {
  const errors: string[] = [];

  for (const source of specSources) {
    try {
      const document = (await SwaggerParser.dereference(source.location)) as OpenAPIV3.Document;
      console.log(`Loaded Firefly III schema from ${source.label}`);
      return document;
    } catch (error) {
      errors.push(`- ${source.label}: ${(error as Error).message}`);
    }
  }

  throw new Error(
    `Failed to load the Firefly III OpenAPI schema. Tried:\n${errors.join(
      '\n'
    )}\nSet FIREFLY_III_OPENAPI_FILE or FIREFLY_III_OPENAPI_URL to a reachable schema file.`
  );
}

/** Enabled actions to generate tools for */
/*
const ENABLED_ACTIONS: {
  tag: string;
  methods?: ('get' | 'post' | 'put' | 'delete' | 'patch')[];
}[] = [
    { tag: 'accounts', methods: ['get', 'put'] },
    { tag: 'attachments', methods: ['get', 'post', 'put', 'delete'] },
    // { tag: 'available_budgets' },
    { tag: 'bills', methods: ['get', 'put', 'post'] },
    { tag: 'categories', methods: ['get', 'put', 'post', 'delete'] },
    { tag: 'search', methods: ['get'] },
    { tag: 'summary', methods: ['get'] },
    { tag: 'tags', methods: ['get', 'put', 'post', 'delete'] },
    { tag: 'transactions', methods: ['get', 'put', 'post', 'delete'] },
  ]

const custonFilterFn = (tool: McpToolDefinition) => {
  const action = ENABLED_ACTIONS.find(action => action.tag === tool.tags[0]);
  if (!action) return false;
  if (action.methods && !action.methods.includes(tool.method as ('get' | 'post' | 'put' | 'delete' | 'patch'))) return false;
  return true;
}
*/

(async () => {
  // Load the OpenAPI document
  const document = await loadOpenApiDocument();

  const tools: McpToolDefinition[] = await getToolsFromOpenApiDocument(document);

  // const securitySchemes = document.components?.securitySchemes;

  // Create the TypeScript code string
  const tsCode = `// This file is auto-generated by scripts/generator.ts

import type { McpToolDefinition } from './types.js';

export const generatedTools: McpToolDefinition[] = ${JSON.stringify(tools, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, tsCode);
  console.log('Successfully generated generated-tools.ts');
})();
